import { APP_NAME } from "../config/app";
import type { NormalizedRoute } from "../types/route";

export const escapeXml = (value: string) =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");

export function routeToGpx(route: NormalizedRoute): string {
  const name = `${APP_NAME} ${(route.actualDistanceMeters / 1000).toFixed(1)} km`;
  const points = route.coordinates
    .map(
      (coordinate) =>
        `    <trkpt lat="${coordinate[1].toFixed(7)}" lon="${coordinate[0].toFixed(7)}">${coordinate.length > 2 ? `<ele>${coordinate[2]?.toFixed(1)}</ele>` : ""}</trkpt>`,
    )
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="${APP_NAME}" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata><name>${escapeXml(name)}</name><desc>Generated by ${APP_NAME}</desc></metadata>
  <trk><name>${escapeXml(name)}</name><trkseg>
${points}
  </trkseg></trk>
</gpx>`;
}

export function downloadGpx(route: NormalizedRoute): void {
  const url = URL.createObjectURL(
    new Blob([routeToGpx(route)], { type: "application/gpx+xml;charset=utf-8" }),
  );
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `looproute-${(route.actualDistanceMeters / 1000).toFixed(1).replace(".", "-")}-km.gpx`;
  anchor.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
}
